# -*- coding: utf-8 -*-

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import unittest, datetime, time

class FunctionalTest(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()

    def tearDown(self):
        self.driver.close()

    # FTI1
    def test_T01_login_required(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        self.assertIn("Identificarse", driver.title)
        #link.send_keys(Keys.DOWN)
        #link.send_keys(Keys.RETURN)
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)

    # FTI2
    def test_T02_add_project(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("add_project").click()
        self.assertIn("Nombre del proyecto:", driver.page_source)
        self.assertIn("Cliente:", driver.page_source)
        driver.find_element_by_id("id_nombre").send_keys('AAAProjectTest')
        driver.find_element_by_id("id_cliente").send_keys('CustomerTest')
        driver.find_element_by_id("id_nombre_del_equipo").send_keys('TeamTest')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Inicio", driver.title)
        self.assertIn("AAAProjectTest", driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("add_project").click()
        self.assertIn("Nombre del proyecto:", driver.page_source)
        self.assertIn("Cliente:", driver.page_source)
        driver.find_element_by_id("id_nombre").send_keys('AAAProjectTest')
        driver.find_element_by_id("id_cliente").send_keys('CustomerTest')
        driver.find_element_by_id("id_nombre_del_equipo").send_keys('TeamTest')
        driver.find_element_by_name("guardar").click()
        self.assertIn("already exists", driver.page_source)

    # FTI13
    def test_T03_add_project_rol(self):
        driver = self.driver
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("see_roles")[0].click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Cliente
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text("Cliente")
        driver.find_element_by_id('id_usuario').send_keys('saul.drago@gmail.com')#Alonso
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Analista
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text("Analista")
        driver.find_element_by_id('id_usuario').send_keys('isaul37@hotmail.es')#saul
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Arquitecto
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text("Arquitecto")
        driver.find_element_by_id('id_usuario').send_keys('isaul37@hotmail.es')#saul
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Desarrollador
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text("Desarrollador")
        driver.find_element_by_id('id_usuario').send_keys('isaul37@hotmail.es')#saul
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Tester
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text("Tester")
        driver.find_element_by_id('id_usuario').send_keys('isaul37@hotmail.es')#saul
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Gerente de calidad
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text("Gerente de calidad")
        driver.find_element_by_id('id_usuario').send_keys('isaul37@hotmail.es')#saul
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Lider de proyecto
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_name("add_rol").click()
        self.assertIn("Rol:", driver.page_source)
        Select(driver.find_element_by_id('id_rol')).select_by_visible_text(u'Líder de proyecto')
        driver.find_element_by_id('id_usuario').send_keys('isaul37@hotmail.es')#saul
        driver.find_element_by_name("guardar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)

    # FTI12
    def test_T04_add_project_event(self):
        driver = self.driver
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("see_events")[0].click()
        self.assertIn("Calendario de eventos registrados", driver.page_source)
        driver.find_elements_by_class_name("add_event")[-1].click()
        self.assertIn("Evento:", driver.page_source)
        self.assertIn("Fecha:", driver.page_source)
        Select(driver.find_element_by_id('id_evento')).select_by_visible_text('Auditoria interna')
        Select(driver.find_element_by_id('id_asistentes')).select_by_visible_text('alonso')
        driver.find_element_by_id("id_hora").clear()
        driver.find_element_by_id("id_hora").send_keys('23:59')
        driver.find_element_by_id("guardar").click()
        self.assertIn("Calendario de eventos registrados", driver.page_source)

    # FTI4
    def test_T05_add_stage_project(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Análisis')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Evaluación')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Diseño')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Desarrollo')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Pruebas')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Liberación')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_fase").click()
        self.assertIn("Fase:", driver.page_source)
        self.assertIn("Fecha de inicio:", driver.page_source)
        Select(driver.find_element_by_id('id_fase')).select_by_visible_text('Cierre')
        driver.find_element_by_name("guardar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

    # FTI6
    def test_T06_add_product_stage(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        time.sleep(0.000000000001)
        #Fase de análisis
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[0].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Documento de requisitos")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Fase de evaluación
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[1].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Documento de gestión de riesgos")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Fase de diseño
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[2].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Diagrama de diseño de sistema")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Fase de desarrollo
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[3].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Código fuente")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Fase de pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[4].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Reporte de pruebas")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Fase de liberación
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[5].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Procedimiento de entrega")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Fase de cierre
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[6].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_element_by_id("agregar_producto").click()
        self.assertIn("Producto de trabajo:", driver.page_source)
        Select(driver.find_element_by_id('id_producto')).select_by_visible_text(u"Documento de cierre de proyecto")
        driver.find_element_by_name("guardar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)

    # FTI9
    def test_T07_add_aceptance_criteria(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        #Documento de requisitos
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[0].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        self.assertIn("Criterios asignados", driver.page_source)
        driver.find_element_by_name("agregar_criterio").click()
        self.assertIn("Criterio:", driver.page_source)
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Documento de gestión de riesgos
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[1].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_criterio").click()
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Diseño de sistema
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, (document.body.scrollHeight/2));")
        driver.find_elements_by_class_name("see_productos")[2].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_criterio").click()
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Código fuente
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, (document.body.scrollHeight/2));")
        driver.find_elements_by_class_name("see_productos")[3].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_criterio").click()
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Plan de pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[4].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_criterio").click()
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #procedimeinto de entrega
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[5].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_criterio").click()
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Documento de cierre
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[6].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_criterio").click()
        Select(driver.find_element_by_id('id_criterio')).select_by_index(1)
        driver.find_element_by_name("guardar").click()
        self.assertIn("Criterios asignados", driver.page_source)

    # FTI10
    def test_T08_add_metric(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        #Documento de requisitos
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[0].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        driver.find_element_by_name("agregar_metrica").click()
        self.assertIn(u'Métrica:', driver.page_source)
        Select(driver.find_element_by_id('id_metrica')).select_by_index(1)
        driver.find_element_by_id('id_indice').send_keys(3)
        driver.find_element_by_id('id_limite_superior').send_keys(10)
        driver.find_element_by_id('id_limite_inferior').send_keys(0)
        driver.find_element_by_name("guardar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Documento de gestión de riesgos
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[1].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_metrica").click()
        Select(driver.find_element_by_id('id_metrica')).select_by_index(1)
        driver.find_element_by_id('id_indice').send_keys(3)
        driver.find_element_by_id('id_limite_superior').send_keys(10)
        driver.find_element_by_id('id_limite_inferior').send_keys(0)
        driver.find_element_by_name("guardar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Diseño de sistema
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[2].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_metrica").click()
        Select(driver.find_element_by_id('id_metrica')).select_by_index(1)
        driver.find_element_by_id('id_indice').send_keys(3)
        driver.find_element_by_id('id_limite_superior').send_keys(10)
        driver.find_element_by_id('id_limite_inferior').send_keys(0)
        driver.find_element_by_name("guardar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Código fuente
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[3].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_metrica").click()
        Select(driver.find_element_by_id('id_metrica')).select_by_index(1)
        driver.find_element_by_id('id_indice').send_keys(3)
        driver.find_element_by_id('id_limite_superior').send_keys(10)
        driver.find_element_by_id('id_limite_inferior').send_keys(0)
        driver.find_element_by_name("guardar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Plan de pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[4].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_metrica").click()
        Select(driver.find_element_by_id('id_metrica')).select_by_index(1)
        driver.find_element_by_id('id_indice').send_keys(3)
        driver.find_element_by_id('id_limite_superior').send_keys(10)
        driver.find_element_by_id('id_limite_inferior').send_keys(0)
        driver.find_element_by_name("guardar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #procedimeinto de entrega
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[5].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_element_by_name("agregar_metrica").click()
        Select(driver.find_element_by_id('id_metrica')).select_by_index(1)
        driver.find_element_by_id('id_indice').send_keys(3)
        driver.find_element_by_id('id_limite_superior').send_keys(10)
        driver.find_element_by_id('id_limite_inferior').send_keys(0)
        driver.find_element_by_name("guardar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Documento de cierre se omite al no tener actividad de verificación de resultados de medición

    # FTF1
    def test_T09_aprove_project(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("aprove_project")[0].click()
        self.assertIn('Nombre del proyecto:', driver.page_source)
        self.assertIn('Cliente:', driver.page_source)
        driver.find_element_by_id("id_estatus").click()
        driver.find_element_by_name("guardar").click()
        self.assertIn("Proyectos registados", driver.page_source)
        #time.sleep(2)

    # FTF1
    def test_T10_show_productos(self):
        driver = self.driver
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_element_by_id("id_username").send_keys('saul')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Proyectos disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        self.assertIn("Fases disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_fase")[1].click()
        self.assertIn("Listado de productos a evaluar", driver.page_source)

    # FTF1
    def test_T11_update_product_file(self):
        driver = self.driver
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_element_by_id("id_username").send_keys('saul')#desarrollador/analista/arquitecto/tester/Líder/gerente
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Proyectos disponibles", driver.page_source)
        #Análisis
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        self.assertIn("Fases disponibles", driver.page_source)
        self.assertIn("Desarrollo", driver.page_source)
        driver.find_elements_by_class_name("see_fase")[0].click()
        self.assertIn("Listado de productos a evaluar", driver.page_source)
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        #Diseño
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        driver.find_elements_by_class_name("see_fase")[1].click()
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        #Evaluación
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        driver.find_elements_by_class_name("see_fase")[2].click()
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        #Desarrollo
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        driver.find_elements_by_class_name("see_fase")[3].click()
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        #Pruebas
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        driver.find_elements_by_class_name("see_fase")[4].click()
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        #Liberación
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        driver.find_elements_by_class_name("see_fase")[5].click()
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        #Cierre
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        driver.find_elements_by_class_name("see_fase")[6].click()
        self.assertIn("Actualizar archivo", driver.page_source)
        driver.find_elements_by_class_name("actualizar_archivo")[0].click()
        self.assertIn("Documento / Imagen elaborado:", driver.page_source)
        driver.find_element_by_id("salir").click()
        #cliente no permite actualizar
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_element_by_id("id_username").send_keys('saul.drago@gmail.com')#cliente
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Proyectos disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        self.assertIn("Fases disponibles", driver.page_source)
        self.assertIn("Desarrollo", driver.page_source)
        driver.find_elements_by_class_name("see_fase")[0].click()
        self.assertIn("Listado de productos a evaluar", driver.page_source)
        self.assertFalse("Actualizar archivo" in driver.page_source)
        """

    # FTF2
    def test_T12_change_aceptance_criteria(self):
        driver = self.driver
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Proyectos disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        self.assertIn("Fases disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_fase")[0].click()
        self.assertIn("Listado de productos a evaluar", driver.page_source)
        driver.find_elements_by_class_name("see_criterios")[0].click()
        self.assertIn(u'Criterios de aceptación de', driver.page_source)
        checkbox = driver.find_elements_by_class_name("check_criteria")[0]
        checkbox.click()
        self.assertTrue(checkbox.is_selected())
"""

    # FTF3
    def test_T13_load_product_measure_char(self):
        driver = self.driver
        driver.get("http:localhost:8000/evaluar/inicio")
        driver.find_element_by_id("id_username").send_keys('Alonso')#cliente
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Proyectos disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_proyecto")[0].click()
        self.assertIn("Fases disponibles", driver.page_source)
        driver.find_elements_by_class_name("see_fase")[1].click()
        self.assertIn("Listado de productos a evaluar", driver.page_source)
        driver.find_elements_by_class_name("see_metricas")[0].click()
        self.assertIn(u'Métricas de', driver.page_source)

    # FTF3
    def test_T14_change_project_status(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("aprove_project")[0].click()
        self.assertIn(u'ATENCIÓN! Cuando el proyecto se marque cómo autorizado', driver.page_source)
        driver.find_element_by_id("id_estatus").click()
        driver.find_element_by_name("guardar").click()
        self.assertIn("Proyectos registados", driver.page_source)

    # FTI11
    def test_T16_delete_metric(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        #Documento de requisitos
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[0].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        driver.find_elements_by_class_name("delete_metric")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Documento de gestión de riesgos
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[1].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_metric")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Diseño de sistema
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[2].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_metric")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Código fuente
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[3].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_metric")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Plan de pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[4].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_metric")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #procedimeinto de entrega
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[5].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_metric")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn(u'Métricas asignadas', driver.page_source)
        #Documento de cierre se omite al no tener actividad de verificación de resultados de merición

    # FTI8
    def test_T15_delete_aceptance_criteria(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[0].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        self.assertIn("Criterios asignados", driver.page_source)
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Diseño de sistema
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[1].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Documento de gestión de riesgos
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("see_productos")[2].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Código fuente
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, (document.body.scrollHeight/2));")
        driver.find_elements_by_class_name("see_productos")[3].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Plan de pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, (document.body.scrollHeight/2));")
        driver.find_elements_by_class_name("see_productos")[4].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Procedimiento de entrega
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[5].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)
        #Documento de cierre
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[6].click()
        driver.find_elements_by_class_name("see_detalle_producto")[0].click()
        driver.find_elements_by_class_name("delete_criteria")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Criterios asignados", driver.page_source)

    # FTI7
    def test_T17_delete_product_stage(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        #Código fuente
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("see_productos")[0].click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        driver.find_elements_by_class_name("delete_product")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #SRS
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[1].click()
        driver.find_elements_by_class_name("delete_product")[0].click()
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Documento de gestión de riesgos
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[2].click()
        driver.find_elements_by_class_name("delete_product")[0].click()
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Diseño de sistema
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[3].click()
        driver.find_elements_by_class_name("delete_product")[0].click()
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Plan de pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[4].click()
        driver.find_elements_by_class_name("delete_product")[0].click()
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Procedimiento de entrega
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[5].click()
        driver.find_elements_by_class_name("delete_product")[0].click()
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)
        #Documento de cierre
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.find_elements_by_class_name("see_productos")[6].click()
        driver.find_elements_by_class_name("delete_product")[0].click()
        driver.find_element_by_id("eliminar").click()
        self.assertIn('Productos de trabajo agregados', driver.page_source)

    # FTI5
    def test_T18_delete_stage_project(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        #Análisis
        driver.find_elements_by_class_name("see_fases")[0].click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        driver.find_elements_by_class_name("delete_fase")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        #Diseño
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("delete_fase")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        #Evaluación
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("delete_fase")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        #Desarrollo
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("delete_fase")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        #Pruebas
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("delete_fase")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        #Liberación
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("delete_fase")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)
        #Cierre
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_fases")[0].click()
        driver.find_elements_by_class_name("delete_fase")[0].click()
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Fases de proyecto registradas", driver.page_source)

    # FTI14
    def test_T19_delete_project_rol(self):
        driver = self.driver
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        #Analista
        driver.find_elements_by_class_name("see_roles")[0].click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Arquitecto
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_roles")[0].click()
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Desarrollador
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_roles")[0].click()
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Tester
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_roles")[0].click()
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Líder de proyecto
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_roles")[0].click()
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Gerente de calidad
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_roles")[0].click()
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)
        #Cliente
        driver.get("http:localhost:8000/administrar/inicio/")
        driver.find_elements_by_class_name("see_roles")[0].click()
        driver.find_elements_by_class_name("delete_rol")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Roles agregados al proyecto", driver.page_source)

    # FTI3
    def test_T20_delete_project(self):
        driver = self.driver
        driver.get("http://localhost:8000/administrar/inicio/")
        driver.find_element_by_id("id_username").send_keys('alonso')
        driver.find_element_by_id("id_password").send_keys('a1e2i3o4u5')
        self.driver.find_element_by_id('login-form').submit()
        self.assertIn("Inicio", driver.title)
        driver.find_elements_by_class_name("delete_project")[0].click()
        self.assertIn('Confirma Eliminar el siguiete registro?', driver.page_source)
        driver.find_element_by_name("eliminar").click()
        self.assertIn("Inicio", driver.title)
        self.assertFalse("AAAProjectTest" in driver.page_source)

if __name__ == "__main__":
    unittest.main()
